# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fc8b9ea3218d6f321ee26b4f87a9de7bac8a3bb9272bee83b5838d66a7bc4798f88a3f6799994c82c11ac474a7ee788c73062fa3bf9be890b250e6a9380d4d

test:
  secret_key_base: 4579e7555f4dbc192ed7d4ecfdcedd4c5727801079782e4fe4776bdce565215f4ac156410b5dc528318939129add6ac8a46b5dd330f0252aa114b25c044abd53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
